on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'zapPilot/frontend-staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: repo-sync/github-sync@v2
        with:
          source_repo: zapPilot/all-weather-frontend
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
