name: Sync to staging repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

          git remote add staging https://x-access-token:${{ secrets.YOUR_GITHUB_TOKEN }}@github.com/zapPilot/frontend-staging.git

          git push -f staging main:main
