name: Sync to staging repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to staging repo
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

          git remote add staging https://${{ secrets.YOUR_GITHUB_TOKEN }}@github.com/zapPilot/frontend-staging.git
          git push -f staging main:main

      - name: Test sync (PR only)
        if: github.event_name == 'pull_request'
        run: |
          echo "This is a PR - would sync to staging on merge"
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git remote add staging https://${{ secrets.YOUR_GITHUB_TOKEN }}@github.com/zapPilot/frontend-staging.git
          echo "Sync test completed successfully"
