name: Sync to staging repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git and push
        run: |
          # Debug: Check if tokens exist
          echo "YOUR_GITHUB_TOKEN exists: ${{ secrets.YOUR_GITHUB_TOKEN != '' }}"
          echo "GITHUB_TOKEN exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "PAT_TOKEN exists: ${{ secrets.PAT_TOKEN != '' }}"

          git config user.name "david30907d"
          git config user.email "davidtnfsh@gmail.com"

          git remote add staging https://x-access-token:${{ secrets.YOUR_GITHUB_TOKEN }}@github.com/zapPilot/frontend-staging.git

          git push -f staging HEAD:main
