name: Run Vitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 7 # Job will timeout after 7 minutes
    env:
      NEXT_PUBLIC_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_CHAIN_ID }}
      NEXT_PUBLIC_BUNDLER_URL: ${{ secrets.NEXT_PUBLIC_BUNDLER_URL }}
      NEXT_PUBLIC_ETHERSPOT_PROJECT_KEY: ${{ secrets.NEXT_PUBLIC_ETHERSPOT_PROJECT_KEY }}
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_SDK_API_URL: ${{ vars.NEXT_PUBLIC_SDK_API_URL }}
      NEXT_PUBLIC_ARBITRUM_RPC_PROVIDER_URL: ${{ secrets.NEXT_PUBLIC_ARBITRUM_RPC_PROVIDER_URL }}
      NEXT_PUBLIC_BASE_RPC_PROVIDER_URL: ${{ secrets.NEXT_PUBLIC_BASE_RPC_PROVIDER_URL }}
      NEXT_PUBLIC_OPTIMISM_RPC_PROVIDER_URL: ${{ secrets.NEXT_PUBLIC_OPTIMISM_RPC_PROVIDER_URL }}
      NEXT_PUBLIC_INTEGRATOR_ID: ${{ secrets.NEXT_PUBLIC_INTEGRATOR_ID }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test
